// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggepvwvijeieffuugrql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnZXB2d3ZpamVpZWZmdXVncnFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzU3MjQsImV4cCI6MjA2Mzc1MTcyNH0.WRIsKfXVuU_WS-HOiwHWWuQeCzvfOLqS3-q-XnJfw7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);